name: Documentation
on:
  pull_request:
    types: [closed]

jobs:
  
  Generation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Javadoc
        run: mvn -B javadoc::javadoc
        
      - name: Deploy doc
        uses: peaceiris/actions-gh-pages@v4
